# Generated by Django 4.0.5 on 2022-06-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Fundraise Category',
                'verbose_name_plural': 'Fundraise Categories',
            },
        ),
        migrations.AddField(
            model_name='fundraise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundraises.fundraisecategory', verbose_name='Category'),
        ),
    ]
