# Generated by Django 4.0.6 on 2022-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0004_alter_fundraise_category_alter_fundraise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraise',
            name='needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Потрібно коштів'),
        ),
        migrations.AddField(
            model_name='fundraise',
            name='raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Зібрано'),
            preserve_default=False,
        ),
    ]
