# Generated by Django 4.0.6 on 2022-07-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0004_alter_fundraise_category_alter_fundraise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='fundraisecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='fundraisecategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва'),
        ),
    ]
