# Generated by Django 4.0.6 on 2022-07-19 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fundraises.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraises', '0005_fundraise_needed_fundraise_raised'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraise',
            options={'verbose_name': 'Збірка', 'verbose_name_plural': 'Збірки'},
        ),
        migrations.AlterModelOptions(
            name='fundraisecategory',
            options={'verbose_name': 'Категорія збірок', 'verbose_name_plural': 'Категорії збірок'},
        ),
        migrations.AlterField(
            model_name='fundraise',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='fundraise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraise', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
    ]
