# Generated by Django 4.0.6 on 2022-07-19 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraises', '0006_alter_fundraise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Зібрано'),
        ),
        migrations.AlterField(
            model_name='fundraise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraise', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
