# Generated by Django 4.0.6 on 2022-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0007_alter_fundraise_raised_alter_fundraise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fundraises', verbose_name='Зображення'),
        ),
    ]
