# Generated by Django 4.0.6 on 2022-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0009_alter_fundraise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='title',
            field=models.CharField(blank=True, default='fundraise', max_length=100, verbose_name='Назва'),
            preserve_default=False,
        ),
    ]
