# Generated by Django 4.0.6 on 2022-07-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0005_fundraisecategory_description_and_more'),
        ('fundraises', '0010_alter_fundraise_title'),
    ]

    operations = [
    ]
