# Generated by Django 4.0.6 on 2022-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraises', '0012_fundraise_is_featured_alter_fundraise_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='fundraisecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Зображення'),
        ),
    ]
